CREATE TABLE [dbo].[Game]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Title VARCHAR(100) NOT NULL,
	Description VARCHAR(MAX),
	[IdGenre] INT NOT NULL
	
	CONSTRAINT FK_Game_Genre FOREIGN KEY (IdGenre) REFERENCES Genre(Id)
	)
